
package org.ponyman.ca;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CaPublisher", targetNamespace = "http://ca.ponyman.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CaPublisher {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCaData", targetNamespace = "http://ca.ponyman.org/", className = "org.ponyman.ca.GetCaData")
    @ResponseWrapper(localName = "getCaDataResponse", targetNamespace = "http://ca.ponyman.org/", className = "org.ponyman.ca.GetCaDataResponse")
    @Action(input = "http://ca.ponyman.org/CaPublisher/getCaDataRequest", output = "http://ca.ponyman.org/CaPublisher/getCaDataResponse")
    public List<Integer> getCaData(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
